export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const CHANGE_PROFILE_PICTURE_REQUEST = 'CHANGE_PROFILE_PICTURE_REQUEST';
export const CHANGE_PROFILE_PICTURE_SUCCESS = 'CHANGE_PROFILE_PICTURE_SUCCESS';
export const CHANGE_PROFILE_PICTURE_FAILURE = 'CHANGE_PROFILE_PICTURE_FAILURE';

export const CHANGE_COVER_PHOTO_REQUEST = 'CHANGE_COVER_PHOTO_REQUEST';
export const CHANGE_COVER_PHOTO_SUCCESS = 'CHANGE_COVER_PHOTO_SUCCESS';
export const CHANGE_COVER_PHOTO_FAILURE = 'CHANGE_COVER_PHOTO_FAILURE';

export const GET_ALL_FEEDS_REQUEST = 'GET_ALL_FEEDS_REQUEST';
export const GET_ALL_FEEDS_SUCCESS = 'GET_ALL_FEEDS_SUCCESS';
export const GET_MORE_FEEDS_SUCCESS = 'GET_MORE_FEEDS_SUCCESS';
export const GET_MORE_FEEDS_REQUEST = 'GET_MORE_FEEDS_REQUEST';
export const GET_ALL_FEEDS_FAILURE = 'GET_ALL_FEEDS_FAILURE';
export const GET_MORE_FEEDS_FAILURE = 'GET_MORE_FEEDS_FAILURE';
export const GET_FEEDS_TOTAL = 'GET_FEEDS_TOTAL';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const POST_ARTICLES_REQUEST = 'POST_ARTICLES_REQUEST';
export const POST_ARTICLES_SUCCESS = 'POST_ARTICLES_SUCCESS';
export const POST_ARTICLES_FAILURE = 'POST_ARTICLES_FAILURE';

export const POST_GIF_REQUEST = 'POST_GIF_REQUEST';
export const POST_GIF_SUCCESS = 'POST_GIF_SUCCESS';
export const POST_GIF_FAILURE = 'POST_GIF_FAILURE';

export const POST_GIF_COMMENT_REQUEST = 'POST_GIF_COMMENT_REQUEST';
export const POST_GIF_COMMENT_SUCCESS = 'POST_GIF_COMMENT_SUCCESS';
export const POST_GIF_COMMENT_FAILURE = 'POST_GIF_COMMENT_FAILURE';

export const POST_ARTICLE_COMMENT_REQUEST = 'POST_ARTICLE_COMMENT_REQUEST';
export const POST_ARTICLE_COMMENT_SUCCESS = 'POST_ARTICLE_COMMENT_SUCCESS';
export const POST_ARTICLE_COMMENT_FAILURE = 'POST_ARTICLE_COMMENT_FAILURE';

export const LIKE_ARTICLES_REQUEST = 'LIKE_ARTICLES_REQUEST';
export const LIKE_ARTICLES_SUCCESS = 'LIKE_ARTICLES_SUCCESS';
export const LIKE_ARTICLES_FAILURE = 'LIKE_ARTICLES_FAILURE';

export const LIKE_GIF_REQUEST = 'LIKE_GIF_REQUEST';
export const LIKE_GIF_SUCCESS = 'LIKE_GIF_SUCCESS';
export const LIKE_GIF_FAILURE = 'LIKE_GIF_FAILURE';

export const GET_SINGLE_GIF_REQUEST = 'GET_SINGLE_GIF_REQUEST';
export const GET_SINGLE_GIF_SUCCESS = 'GET_SINGLE_GIF_SUCCESS';
export const GET_SINGLE_GIF_FAILURE = 'GET_SINGLE_GIF_FAILURE';

export const GET_SINGLE_ARTICLE_REQUEST = 'GET_SINGLE_ARTICLE_REQUEST';
export const GET_SINGLE_ARTICLE_SUCCESS = 'GET_SINGLE_ARTICLE_SUCCESS';
export const GET_SINGLE_ARTICLE_FAILURE = 'GET_SINGLE_ARTICLE_FAILURE';
