export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const CHANGE_PROFILE_PICTURE_REQUEST = 'CHANGE_PROFILE_PICTURE_REQUEST';
export const CHANGE_PROFILE_PICTURE_SUCCESS = 'CHANGE_PROFILE_PICTURE_SUCCESS';
export const CHANGE_PROFILE_PICTURE_FAILURE = 'CHANGE_PROFILE_PICTURE_FAILURE';

export const CHANGE_COVER_PHOTO_REQUEST = 'CHANGE_COVER_PHOTO_REQUEST';
export const CHANGE_COVER_PHOTO_SUCCESS = 'CHANGE_COVER_PHOTO_SUCCESS';
export const CHANGE_COVER_PHOTO_FAILURE = 'CHANGE_COVER_PHOTO_FAILURE';

export const GET_ALL_FEEDS_REQUEST = 'GET_ALL_FEEDS_REQUEST';
export const GET_ALL_FEEDS_SUCCESS = 'GET_ALL_FEEDS_SUCCESS';
export const GET_ALL_FEEDS_FAILURE = 'GET_ALL_FEEDS_FAILURE';
